name: 🐍 CI
on:
  pull_request:
  push:
  schedule:
    - cron: '7 1 * * 0'

jobs:

  lint:
    name: Linters and checkers
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'schedule' }}

    strategy:
      matrix:
        python_version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv setuptools
          python -m pipenv install --system --deploy --dev

      - name: Run prospector
        run: prospector

  publish-package:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'schedule' }}
    needs:
      - lint

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Python 3.7
        uses: actions/setup-python@master
        with:
          python-version: 3.7

      # TODO: add `pyproject.toml` according to PEP 517/PEP 518
      # - name: Install pep517
      #   run: python -m pip install pep517 --user
      # - name: Build a binary wheel and a source tarball
      #   run: python -m pep517.build --source --binary --out-dir dist/ .

      - name: Install requirements
        run: python -m pip install --upgrade --user setuptools wheel twine

      - name: Bump version
        run: sed -i "$ s/$/.${GITHUB_RUN_NUMBER}/" version.txt

      - name: Prepare packages
        run: python setup.py sdist bdist_wheel

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}

  publish-image:
    name: 📦 (Re)Build and publish Docker image
    runs-on: ubuntu-latest

    needs:
      - lint

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Docker Meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push to GitHub Registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
